// frontend/src/components/Register.vue
<template>
  <div class="min-h-screen flex items-center justify-center">
    <div class="w-full max-w-md bg-white rounded-lg shadow p-6">
      <h1 class="text-2xl font-semibold mb-4">Create account</h1>
      <form @submit.prevent="onSubmit" class="space-y-4">
        <input v-model="name" type="text" placeholder="Full name" class="w-full border rounded px-3 py-2" required />
        <input v-model="email" type="email" placeholder="Email" class="w-full border rounded px-3 py-2" required />
        <input v-model="password" type="password" placeholder="Password" class="w-full border rounded px-3 py-2" required />
        <input v-model="password_confirmation" type="password" placeholder="Confirm Password" class="w-full border rounded px-3 py-2" required />
        <button :disabled="loading" class="w-full bg-green-600 text-white rounded py-2">
          {{ loading ? 'Signing up...' : 'Sign up' }}
        </button>
        <p v-if="error" class="text-red-600 text-sm">{{ error }}</p>
      </form>
      <p class="mt-4 text-sm">Have an account? <router-link to="/login" class="text-blue-600">Sign in</router-link></p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '../stores/auth';

const store = useAuthStore();
const router = useRouter();

const name = ref('');
const email = ref('');
const password = ref('');
const password_confirmation = ref('');
const loading = ref(false);
const error = ref(null);

async function onSubmit() {
  loading.value = true; error.value = null;
  try {
    await store.register({ name: name.value, email: email.value, password: password.value, password_confirmation: password_confirmation.value });
    router.push('/dashboard');
  } catch (e) {
    error.value = store.error || 'Registration failed';
  } finally {
    loading.value = false;
  }
}
</script>

// frontend/src/app/components/auth/register/register.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  registerForm: FormGroup;
  isLoading = signal(false);
  errorMessage = signal('');

  passwordMatchValidator(form: FormGroup): { [key: string]: boolean } | null {
    const password = form.get('password');
    const passwordConfirmation = form.get('password_confirmation');

    if (!password || !passwordConfirmation) {
      return null;
    }

    return password.value === passwordConfirmation.value ? null : { passwordMismatch: true };
  }

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.registerForm = this.fb.group({
      first_name: ['', Validators.required],
      last_name: ['', Validators.required],
      other_names: [''],
      email: ['', [Validators.required, Validators.email]],
      phone: [''],
      address: [''],
      password: ['', [Validators.required, Validators.minLength(8)]],
      password_confirmation: ['', Validators.required]
    }, { validators: this.passwordMatchValidator });
  }

  onSubmit(): void {
    if (this.registerForm.valid) {
      this.isLoading.set(true);
      this.errorMessage.set('');

      this.authService.register(this.registerForm.value).subscribe({
        next: () => {
          this.router.navigate(['/dashboard']);
        },
        error: (error) => {
          this.errorMessage.set(error.error?.message || 'Registration failed');
          this.isLoading.set(false);
        }
      });
    }
  }
}
<div class="min-h-screen flex items-center justify-center bg-gray-50">
    <div class="card register-card">
        <div class="text-center mb-4">
            <h2 class="register-title">
                Create your account
            </h2>
        </div>
        <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
            <div class="name-grid">
                <div class="form-group mb-0">
                    <label for="first_name" class="form-label">First Name</label>
                    <input id="first_name" type="text" formControlName="first_name" class="form-input"
                        [class.border-red-600]="registerForm.get('first_name')?.invalid && registerForm.get('first_name')?.touched" />
                </div>
                <div class="form-group mb-0">
                    <label for="last_name" class="form-label">Last Name</label>
                    <input id="last_name" type="text" formControlName="last_name" class="form-input"
                        [class.border-red-600]="registerForm.get('last_name')?.invalid && registerForm.get('last_name')?.touched" />
                </div>
            </div>

            <div class="form-group">
                <label for="other_names" class="form-label">Other Names (Optional)</label>
                <input id="other_names" type="text" formControlName="other_names" class="form-input" />
            </div>

            <div class="form-group">
                <label for="email" class="form-label">Email</label>
                <input id="email" type="email" formControlName="email" class="form-input"
                    [class.border-red-600]="registerForm.get('email')?.invalid && registerForm.get('email')?.touched" />
            </div>

            <div class="form-group">
                <label for="phone" class="form-label">Phone (Optional)</label>
                <input id="phone" type="tel" formControlName="phone" class="form-input" />
            </div>

            <div class="form-group">
                <label for="address" class="form-label">Address (Optional)</label>
                <textarea id="address" formControlName="address" class="form-input" rows="2"></textarea>
            </div>

            <div class="form-group">
                <label for="password" class="form-label">Password</label>
                <input id="password" type="password" formControlName="password" class="form-input"
                    [class.border-red-600]="registerForm.get('password')?.invalid && registerForm.get('password')?.touched" />
                <div *ngIf="registerForm.get('password')?.invalid && registerForm.get('password')?.touched"
                    class="error">
                    Password must be at least 8 characters
                </div>
            </div>

            <div class="form-group">
                <label for="password_confirmation" class="form-label">Confirm Password</label>
                <input id="password_confirmation" type="password" formControlName="password_confirmation"
                    class="form-input"
                    [class.border-red-600]="registerForm.get('password_confirmation')?.invalid && registerForm.get('password_confirmation')?.touched" />
                <div *ngIf="registerForm.get('password_confirmation')?.invalid && registerForm.get('password_confirmation')?.touched"
                    class="error">
                    Please confirm your password
                </div>
                <div *ngIf="registerForm.hasError('passwordMismatch') && registerForm.get('password_confirmation')?.touched"
                    class="error">
                    Passwords do not match
                </div>
            </div>

            <div *ngIf="errorMessage()" class="error text-center mb-4">
                {{ errorMessage() }}
            </div>

            <button type="submit" [disabled]="registerForm.invalid || isLoading()" class="btn btn-primary register-btn">
                {{ isLoading() ? 'Creating account...' : 'Create account' }}
            </button>

            <div class="text-center mt-4">
                <p class="signin-prompt">
                    Already have an account?
                    <a routerLink="/login" class="signin-link">
                        Sign in
                    </a>
                </p>
            </div>
        </form>
    </div>
</div>
