// frontend/src/app/components/auth/login/login.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  loginForm: FormGroup;
  isLoading = signal(false);
  errorMessage = signal('');

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required]
    });
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      this.isLoading.set(true);
      this.errorMessage.set('');

      this.authService.login(this.loginForm.value).subscribe({
        next: () => {
          this.router.navigate(['/dashboard']);
        },
        error: (error) => {
          this.errorMessage.set(error.error?.message || 'Login failed');
          this.isLoading.set(false);
        }
      });
    }
  }
}
<div class="min-h-screen flex items-center justify-center bg-gray-50">
    <div class="card login-card">
        <div class="text-center mb-4">
            <h2 class="login-title">
                Sign in to Tumi Configurator
            </h2>
        </div>
        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label for="email" class="form-label">Email</label>
                <input id="email" type="email" formControlName="email" class="form-input"
                    [class.border-red-600]="loginForm.get('email')?.invalid && loginForm.get('email')?.touched" />
                <div *ngIf="loginForm.get('email')?.invalid && loginForm.get('email')?.touched" class="error">
                    Email is required and must be valid
                </div>
            </div>

            <div class="form-group">
                <label for="password" class="form-label">Password</label>
                <input id="password" type="password" formControlName="password" class="form-input"
                    [class.border-red-600]="loginForm.get('password')?.invalid && loginForm.get('password')?.touched" />
                <div *ngIf="loginForm.get('password')?.invalid && loginForm.get('password')?.touched" class="error">
                    Password is required
                </div>
            </div>

            <div *ngIf="errorMessage()" class="error text-center mb-4">
                {{ errorMessage() }}
            </div>

            <button type="submit" [disabled]="loginForm.invalid || isLoading()" class="btn btn-primary login-btn">
                {{ isLoading() ? 'Signing in...' : 'Sign in' }}
            </button>

            <div class="text-center mt-4">
                <p class="signup-prompt">
                    Don't have an account?
                    <a routerLink="/register" class="signup-link">
                        Sign up
                    </a>
                </p>
            </div>
        </form>
    </div>
</div>

// frontend/src/components/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center">
    <div class="w-full max-w-md bg-white rounded-lg shadow p-6">
      <h1 class="text-2xl font-semibold mb-4">Sign in</h1>
      <form @submit.prevent="onSubmit" class="space-y-4">
        <input v-model="email" type="email" placeholder="Email" class="w-full border rounded px-3 py-2" required />
        <input v-model="password" type="password" placeholder="Password" class="w-full border rounded px-3 py-2" required />
        <button :disabled="loading" class="w-full bg-blue-600 text-white rounded py-2">
          {{ loading ? 'Signing in...' : 'Sign in' }}
        </button>
        <p v-if="error" class="text-red-600 text-sm">{{ error }}</p>
      </form>
      <p class="mt-4 text-sm">No account? <router-link to="/register" class="text-blue-600">Sign up</router-link></p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '../stores/auth';

const store = useAuthStore();
const router = useRouter();

const email = ref('');
const password = ref('');
const loading = ref(false);
const error = ref(null);

async function onSubmit() {
  loading.value = true; error.value = null;
  try {
    await store.login({ email: email.value, password: password.value });
    router.push('/dashboard');
  } catch (e) {
    error.value = store.error || 'Login failed';
  } finally {
    loading.value = false;
  }
}
</script>
